#SecureServer by xtechgamer735
#Please Leave this file, it will sort its self out!
disableCommands: true
disableChat: false
disableBuild: false

room: #Please set with /setroom
out: #Please set with /setout

email:
    enabled: false
    SMTPserver: smtp.gmail.com
    emailaddress: your@email.com
    password: changeme
    servername: ServerName
