name: SecureServer
main: com.xtechgamer735.SecureServer.Main
version: 1.0
author: xtechgamer735

commands:
    setpassword:
    changepassword:
    setroom:
    login:
    setout:
    secureserver:
        aliases: [secure, ss]
    removepassword:
    setemail:
    forgotpassword:


permissions:
    secureserver.admin:
        default: Op
    secureserver.user:
        default: true